### ISSUE TITLE
[Bug] 不能正确处理行内数学公式

### ISSUE THREAD

**Issue by shawlleyw** [OI-wiki/remark-typst#1]
使用oi-wiki-export-typst对OI-wiki进行typst导出的时候，发现行内数学公式处理没有得到处理，返回的是一个null
```shell
~/OI-Wiki-export/oi-wiki-export-typst $ node index.js ~/OI-wiki/
[INFO] Processing snippets
[INFO] Checking for typ/ directory
[INFO] Exporting OI Wiki from directory: /home/wsy/OI-wiki/
[INFO] Config file: /home/wsy/OI-wiki/mkdocs.yml
[INFO] Exporting: 简介
[INFO] Exporting: Getting Started
[ERROR] Error occurred when processing image file "/home/wsy/OI-wiki/docs/images/wordArt.webp"
[INFO] Exporting: 关于本项目
[INFO] Exporting: 如何参与
[ERROR] Error occurred when processing image file "/home/wsy/OI-wiki/docs/intro/images/deploy_preview.png"
[INFO] Exporting: OI Wiki 不是什么
[INFO] Exporting: 格式手册
file:///home/wsy/OI-Wiki-export/remark-typst/lib/compiler.js:381
        return `$${texmath.stdout.toString('utf8').trimEnd()}$`
                                  ^

TypeError: Cannot read properties of null (reading 'toString')
    at parse (file:///home/wsy/OI-Wiki-export/remark-typst/lib/compiler.js:381:35)
    at Array.map (<anonymous>)
    at all (file:///home/wsy/OI-Wiki-export/remark-typst/lib/util.js:6:24)
    at parse (file:///home/wsy/OI-Wiki-export/remark-typst/lib/compiler.js:196:25)
    at Array.map (<anonymous>)
    at all (file:///home/wsy/OI-Wiki-export/remark-typst/lib/util.js:6:24)
    at parse (file:///home/wsy/OI-Wiki-export/remark-typst/lib/compiler.js:267:16)
    at Array.map (<anonymous>)
    at all (file:///home/wsy/OI-Wiki-export/remark-typst/lib/util.js:6:24)
    at parse (file:///home/wsy/OI-Wiki-export/remark-typst/lib/compiler.js:261:28)
```

**Comment by shawlleyw** [comment]
另外想问一下，目前OI wiki导出typst能够完整跑通吗？

我打算添加tabbed语法的导出

**Comment by Enter-tainer** [comment]
能跑通啊 ci就能跑

**Comment by Enter-tainer** [comment]
这个是你没装那个版本的texmath，你去看看ci文件怎么搞的，装一下
